name: Build and test
on:
  pull_request:
  merge_group:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out'
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          foo.md
        sparse-checkout-cone-mode: false
    - name: 'Test contents'
      run: grep "hello" $GITHUB_WORKSPACE/foo.md
